-- AlterTable
ALTER TABLE "Farmer" ADD COLUMN     "fatRate" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "fixedRate" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "snfRate" DOUBLE PRECISION NOT NULL DEFAULT 0;
